#!/bin/bash
# Auto-checkpoint: runs on every Stop event.
# Writes .agent/HANDOFF_STATE.md and pushes to the current branch.
# No manual trigger needed — this just happens.

cd "$(git rev-parse --show-toplevel 2>/dev/null)" || exit 0

BRANCH=$(git branch --show-current 2>/dev/null || echo "unknown")
DATE=$(date "+%Y-%m-%d %H:%M %Z")
COMMITS=$(git log --oneline -10 2>/dev/null || echo "none")
STATUS=$(git status --short 2>/dev/null || echo "")

mkdir -p .agent

cat > .agent/HANDOFF_STATE.md <<EOF
# Handoff State
**Updated:** $DATE
**Branch:** \`$BRANCH\`

## Recent Commits
\`\`\`
$COMMITS
\`\`\`

## Working State
\`\`\`
${STATUS:-clean working tree}
\`\`\`

## Decisions
- Session checkpoint created
- Work state preserved for context continuity

## Next Steps
- Review working state changes
- Continue development from last known state
- Run tests if changes are significant

---
*Auto-generated by Stop hook. Read this at session start to resume context.*
EOF

git add .agent/HANDOFF_STATE.md

# Only commit if the file actually changed
if git diff --cached --name-only | grep -q "HANDOFF_STATE.md"; then
  git commit -m "chore: session checkpoint [$(date '+%H:%M')]" .agent/HANDOFF_STATE.md 2>&1

  # Push ONLY when the checkpoint commit is the sole unpushed commit.
  #
  # Why: `git push` ships the WHOLE branch, not just this commit. If real source
  # commits are sitting unpushed locally, an automated Stop-hook push would shove
  # them to origin at an unpredictable moment — triggering deploy.yml and, via
  # cancel-in-progress, cancelling whatever CI run is live. That's how checkpoint
  # pushes were silently kicking off / killing deploys.
  #
  # So: only auto-push when the single unpushed commit is THIS checkpoint (whose
  # only path is .agent/HANDOFF_STATE.md, already covered by paths-ignore and thus
  # CI-inert). If anything else is unpushed, leave the whole branch alone and let
  # the user push real work deliberately. Fails quietly offline; never force-pushes.
  UPSTREAM=$(git rev-parse --abbrev-ref --symbolic-full-name '@{u}' 2>/dev/null || echo "")
  if [ -n "$UPSTREAM" ]; then
    UNPUSHED=$(git log "$UPSTREAM"..HEAD --name-only --pretty=format: 2>/dev/null | grep -v '^$' | sort -u)
    # Push only if the sole unpushed path is the checkpoint file.
    if [ "$UNPUSHED" = ".agent/HANDOFF_STATE.md" ]; then
      git push origin "$BRANCH" 2>/dev/null || true
    fi
  fi
fi