import { APPROVED_MODELS, INTELLIGENCE_MODELS } from './intelligence-models';

export const AI_MODELS = {
    ...APPROVED_MODELS,
    TEXT: {
        AGENT: APPROVED_MODELS.TEXT_AGENT,
        FAST: APPROVED_MODELS.TEXT_FAST,
        LITE: APPROVED_MODELS.TEXT_LITE,
    },
    IMAGE: {
        GEN: APPROVED_MODELS.IMAGE_GEN,
        FAST: APPROVED_MODELS.IMAGE_FAST,
    },
    VIDEO: {
        PRO: APPROVED_MODELS.VIDEO_PRO,
        FAST: APPROVED_MODELS.VIDEO_FAST,
        LITE: APPROVED_MODELS.VIDEO_LITE,
    },
} as const;

export { APPROVED_MODELS, INTELLIGENCE_MODELS };
